version: '3.3'

services:
  sdg_sb_db:
    image: sdg_sb-db
    build: .docker/db/
    volumes:
      - .data/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=snowball-bot
      - MYSQL_PASSWORD=superball-superpassword
      - MYSQL_DATABASE=snowball-bot
      - DATA_SAVE_PATH=/var/lib/mysql
    restart: always
  sdg_sb_redis:
    image: redis:latest
    volumes:
      - .data/redis/:/data
    ports:
      - 6379:6379
  sdg_sb_bot:
    depends_on:
      - sdg_sb_db
      - sdg_sb_redis
    image: sdg_sb-bot
    build: .
    restart: on-failure
    volumes:
      - .data/snowball/configs:/opt/app/config
    environment:
      - NODE_ENV=production
      - REDIS_HOST=sdg_sb_redis
      - DB_HOST=sdg_sb_db
      - DB_NAME=snowball-bot
      - DB_USER=snowball-bot
      - DB_PASSWD=superball-superpassword

